query SearchBoughtProducts($pageable: PageableInput!, $sort: SortInput!) {
    searchBoughtProducts(pageable: $pageable, sort: $sort) {
        content {
            id
            productId
            name
            description
            category
            imageUrl
            date
            price {
                amount
                currency
            }
        }
        isFirstPage
        isLastPage
    }
}