query SearchProducts($filters: [SearchFilter]!, $page: Page!, $sort: Sort!) {
    searchProducts(filters: $filters, page: $page, sort: $sort) {
        id
        name
        category
        tags
        description
        ownerId
        price {
            amount
            currency
        }
        quantity
        productScore {
            averageScore
            reviewsCount
        }
        imageUrl
    }
} 