query SearchProducts {
    searchProducts(filters: [
        {
            fieldName: "name"
            searchOperation: LIKE
            fieldValue: "a"
        }
    ],
    page: {
        offset: 0,
        limit: 10
    },
    sort: {
        fieldName: "name"
        sortDirection: ASC
    }
    ) {
        id
        name
    }
}