query SearchProducts {
    searchProducts(filters: [
        {
            fieldName: "name"
            searchOperation: LIKE
            fieldValue: "a"
        }
    ]) {
        id
        name
    }
}